services:

  billing-api:
    container_name: billing-api
    image: billing-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url":"jdbc:mysql://billing-db:3306/billing-db-docker?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8",                               
          "spring.datasource.username":"root",
          "spring.datasource.password":"admin",
          "spring.datasource.driver-class-name":"com.mysql.cj.jdbc.Driver",
          "spring.jpa.database-platform":"org.hibernate.dialect.MySQLDialect", 
          "spring.jpa.show-sql":"true",
          "spring.jpa.hibernate.ddl-auto":"update"       
        }'
    networks:
      - spring-network
    depends_on:
      - billing-db

  billing-db:
    container_name: billing-db
    image: mysql:latest
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - /opt/mysql_data:/var/lib/mysql
      - /init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: billing-db-docker
      #MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_ALLOW_EMPTY_PASSWORD: YES
    restart: always
    ports:
      - "3306:3306"

    networks:
      - spring-network

volumes:
  mysql_data:

networks:
  spring-network:
    driver: bridge







